version: "3.5"

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: as
      MYSQL_PASSWORD: as
      MYSQL_DATABASE: asDatabase
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      MYSQL_USER: as
      MYSQL_PASSWORD: as
      MYSQL_DATABASE: asDatabase

  app:
    build: .
    depends_on:
      - "db"
